=== cocoJamboo/spring-tutorials/spring-capgemini-jaxb/src/main/xsd/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Adrian Lapierre (SoftProject) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.softproject.com.pl/commons/model/invoice" targetNamespace="http://www.softproject.com.pl/commons/model/invoice">
	<xs:element name="invoice">
		<xs:annotation>
			<xs:documentation>Główny element dokumentu</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="seller" type="xs:string">
					<xs:annotation>
						<xs:documentation>Dane sprzedawcy</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="buyer" type="xs:string">
					<xs:annotation>
						<xs:documentation>Dane nabywcy</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="place-of-issue" type="xs:string">
					<xs:annotation>
						<xs:documentation>miejsce wystawienia faktury</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="issue-date" type="xs:date">
					<xs:annotation>
						<xs:documentation>data wystawienia faktury</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="sell-date" type="xs:date">
					<xs:annotation>
						<xs:documentation>data wykonania usługi / dostarczenia towaru</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="invoice-number" type="xs:string">
					<xs:annotation>
						<xs:documentation>numer faktury</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="items">
					<xs:annotation>
						<xs:documentation>pozycje faktury</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="no" type="xs:int">
											<xs:annotation>
												<xs:documentation>lp na dokumencie</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="code" type="xs:string">
											<xs:annotation>
												<xs:documentation>kod produktu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="name" type="xs:string">
											<xs:annotation>
												<xs:documentation>nazwa produktu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="foreign-name" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>nazwa produtku w jęcyku obcym</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="qty" type="xs:double">
											<xs:annotation>
												<xs:documentation>ilość sztuk produktu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="unit-name" type="xs:string">
											<xs:annotation>
												<xs:documentation>jednostka miary produktu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="foreign-unit-name" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>jednostka miary w języku obcym</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="currency" type="currencyType">
											<xs:annotation>
												<xs:documentation>waluta w języku dokumentu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="foreign-curency" type="currencyType" minOccurs="0">
											<xs:annotation>
												<xs:documentation>waluta kraju dostawy</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="net-value" type="xs:double">
											<xs:annotation>
												<xs:documentation>wartość netto w walicie dokumentu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="foreign-net-value" type="xs:double" minOccurs="0">
											<xs:annotation>
												<xs:documentation>wartość netto w walucie obcej</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="vat-rate" type="xs:double">
											<xs:annotation>
												<xs:documentation>wartość podatku w kraju wystwienia dokumentu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="net-amount" type="xs:double">
											<xs:annotation>
												<xs:documentation>kwota netto (ilość razy wartość) w walicie dokumentu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="foreign-net-amount" type="xs:double" minOccurs="0">
											<xs:annotation>
												<xs:documentation>kwota netto w walucie obcej</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="vat-amount" type="xs:double">
											<xs:annotation>
												<xs:documentation>wartość podatku VAT w kraju wystawienia faktury</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="gross-amount" type="xs:double">
											<xs:annotation>
												<xs:documentation>wartość brutto w walucie dokumentu</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="foreign-gross-amount" type="xs:double" minOccurs="0">
											<xs:annotation>
												<xs:documentation>wartość brutto w walucie obcej</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="weight" type="xs:double" minOccurs="0">
											<xs:annotation>
												<xs:documentation>waga</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="item-group-name" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>nazwa grupy produtków - zastosowanie do generowania zestawienia sprzedaży</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="item-group-id" type="xs:int" minOccurs="0">
											<xs:annotation>
												<xs:documentation>identyfiator grupy produtków - zastosowanie do generowania zestawienia sprzedaży</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="foreign-vat-amount" type="xs:double" minOccurs="0">
											<xs:annotation>
												<xs:documentation>wartość podatku VAT w kraju dostawy</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="summary">
					<xs:annotation>
						<xs:documentation>podsumowanie dokumentu</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="total-amount" type="xs:double">
								<xs:annotation>
									<xs:documentation>całkowita wartość faktury brutto</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="currency" type="currencyType">
								<xs:annotation>
									<xs:documentation>waluta dokument</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="foreign-currency" type="currencyType" minOccurs="0">
								<xs:annotation>
									<xs:documentation>waluta obca</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="currency-rate" type="xs:double" minOccurs="0">
								<xs:annotation>
									<xs:documentation>zastosowany kurs waluty</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="total-amount-in-words" type="xs:string">
								<xs:annotation>
									<xs:documentation>wartość faktury słownie w języku dokumentu</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="left-to-pay" type="xs:double">
								<xs:annotation>
									<xs:documentation>pozostało do zapłaty</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="payment-date" type="xs:date">
								<xs:annotation>
									<xs:documentation>data płatności</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="days-to-pay" type="xs:int">
								<xs:annotation>
									<xs:documentation>termin zapłaty</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="signer" type="xs:string">
								<xs:annotation>
									<xs:documentation>podpis osoby wystawiającej fakturę</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="net-value" type="xs:double">
								<xs:annotation>
									<xs:documentation>całkowita wartośc netto w walucie dokuemntu </xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="foreign-net-value" type="xs:double" minOccurs="0">
								<xs:annotation>
									<xs:documentation>całkowita wartość netto w walucie obcej</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="tax-value" type="xs:double">
								<xs:annotation>
									<xs:documentation>wartość podatku w kraju</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="foreign-tax-value" type="xs:double" minOccurs="0">
								<xs:annotation>
									<xs:documentation>wartośc podatku za granicą</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="gross-value" type="xs:double">
								<xs:annotation>
									<xs:documentation>wartość do zapłaty</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="foreign-gross-value" type="xs:double" minOccurs="0">
								<xs:annotation>
									<xs:documentation>wartość do zapąty w walucie obcej</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="tax-rate" type="xs:double" minOccurs="0">
								<xs:annotation>
									<xs:documentation>stawka podatku</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="grouping" minOccurs="0">
					<xs:annotation>
						<xs:documentation>grupowania, które należy zastosować w dokumecie zestawienie sprzedaży</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item-group" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:int" use="required">
										<xs:annotation>
											<xs:documentation>id grupy towarów</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>nazwa grupy towatów</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="qty" type="xs:double" use="required">
										<xs:annotation>
											<xs:documentation>zagregowana iliść</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="unit-name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>nazwa jednostki</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="weight" type="xs:double" use="required">
										<xs:annotation>
											<xs:documentation>waga</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="currency" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>waluta</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="net-amount" type="xs:double" use="required">
										<xs:annotation>
											<xs:documentation>wartość netto</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="vat-rate" type="xs:double" use="required">
										<xs:annotation>
											<xs:documentation>stawka VAT</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="gross-amount" type="xs:double" use="required">
										<xs:annotation>
											<xs:documentation>wartość brutto</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="no" type="xs:int">
										<xs:annotation>
											<xs:documentation>lp na dokumencie zestawienia</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="currencyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EUR"/>
			<xs:enumeration value="PLN"/>
			<xs:enumeration value="USD"/>
			<xs:enumeration value="GBP"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== cocoJamboo/spring-tutorials/spring-capgemini-jaxb/src/main/resources/FS 1_MAG_05_2012.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:invoice xmlns:ns2="http://www.softproject.com.pl/commons/model/invoice" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:schemaLocation="http://www.softproject.com.pl/commons/model/invoice http://schema.softproject.com.pl/commons-invoice/invoice.xsd">
    <seller>SoftProject Sp. z o.o.
Warszawska 109  
05-092 Łomianki
NIP: PL xxx-xxx-xx-xx</seller>
    <buyer>Company
145, street 
75006 Paris
NIP: FR xxxxxxxxxx</buyer>
    <place-of-issue></place-of-issue>
    <issue-date>2012-05-06Z</issue-date>
    <sell-date>2012-05-06Z</sell-date>
    <invoice-number>FS 1/05/2012</invoice-number>
    <items>
        <item>
            <no>1</no>
            <code>1/20/1</code>
            <name>medalik</name>
            <foreign-name>Médaillon</foreign-name>
            <qty>50.0</qty>
            <unit-name>szt.</unit-name>
            <foreign-unit-name>unit</foreign-unit-name>
            <currency>PLN</currency>
            <foreign-curency xsi:type="ns2:currencyType">EUR</foreign-curency>
            <net-value>33.5</net-value>
            <foreign-net-value>8.0</foreign-net-value>
            <vat-rate>0.0</vat-rate>
            <net-amount>1675.2</net-amount>
            <foreign-net-amount>400.0</foreign-net-amount>
            <vat-amount>0.0</vat-amount>
            <gross-amount xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:double">1675.2</gross-amount>
            <foreign-gross-amount xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:double">400.0</foreign-gross-amount>
            <foreign-vat-amount>11.0</foreign-vat-amount>
        </item>
        <item>
            <no>2</no>
            <code>2/20/1</code>
            <name>koniczynka</name>
            <foreign-name>Trèfle</foreign-name>
            <qty>50.0</qty>
            <unit-name>szt.</unit-name>
            <foreign-unit-name>unit</foreign-unit-name>
            <currency>PLN</currency>
            <foreign-curency xsi:type="ns2:currencyType">EUR</foreign-curency>
            <net-value>29.32</net-value>
            <foreign-net-value>7.0</foreign-net-value>
            <vat-rate>0.0</vat-rate>
            <net-amount>1465.8</net-amount>
            <foreign-net-amount>350.0</foreign-net-amount>
            <vat-amount>0.0</vat-amount>
            <gross-amount xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:double">1465.8</gross-amount>
            <foreign-gross-amount xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:double">350.0</foreign-gross-amount>
            <foreign-vat-amount>11.0</foreign-vat-amount>
        </item>
        <item>
            <no>3</no>
            <code>3/20/1</code>
            <name>serce</name>
            <foreign-name>Coeur</foreign-name>
            <qty>100.0</qty>
            <unit-name>szt.</unit-name>
            <foreign-unit-name>unit</foreign-unit-name>
            <currency>PLN</currency>
            <foreign-curency xsi:type="ns2:currencyType">EUR</foreign-curency>
            <net-value>33.5</net-value>
            <foreign-net-value>8.0</foreign-net-value>
            <vat-rate>0.0</vat-rate>
            <net-amount>3350.4</net-amount>
            <foreign-net-amount>800.0</foreign-net-amount>
            <vat-amount>0.0</vat-amount>
            <gross-amount xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:double">3350.4</gross-amount>
            <foreign-gross-amount xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:double">800.0</foreign-gross-amount>
            <foreign-vat-amount>11.0</foreign-vat-amount>
        </item>
    </items>
    <summary>
        <total-amount>4840.0</total-amount>
        <currency>PLN</currency>
        <foreign-currency>EUR</foreign-currency>
        <currency-rate>4.188</currency-rate>
        <total-amount-in-words>cztery tysiące osiemset czterdzieści EUR 0/100</total-amount-in-words>
        <left-to-pay>4840.0</left-to-pay>
        <payment-date>2012-06-05Z</payment-date>
        <days-to-pay>0</days-to-pay>
        <signer>Adrian Lapierre</signer>
        <net-value>20269.92</net-value>
        <foreign-net-value>4840.0</foreign-net-value>
        <tax-value>0.0</tax-value>
        <foreign-tax-value>0.0</foreign-tax-value>
        <gross-value>20269.92</gross-value>
        <foreign-gross-value>4840.0</foreign-gross-value>
    </summary>
</ns2:invoice>
